sudo: required
services:
    - docker


before_install:
  - docker build -t giakoumis/docker-react -f Dockerfile.dev .


script:
  - docker run giakoumis/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-319340425542"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_ACCESS_KEY"